Feature/notification item
peaksoft-school/js6-task-tracker pull request #1
Opened 2022-10-06 04:53 UTC by Kamchybekk

2022-10-06 06:43 UTC, songhee24 requested changes

2022-10-06 06:43 UTC, songhee24 commented on src/Components/UI/Button.jsx
> +const Btn = ({ title, onClick, color }) => {
Maybe you should call this Button ?

2022-10-06 06:43 UTC, songhee24 commented on src/Components/UI/Button.jsx
> +    <Button onClick={onClick} color={color}>
And Why are you created the button is the branch called "notification-item"

2022-10-06 06:43 UTC, songhee24 commented on src/Components/UI/NotificationItem.jsx
> +      <DateAdded>Sep 15 at 13:23 PM</DateAdded>
should we use another package for username and useravatar components ?

2022-10-06 06:43 UTC, songhee24 commented on src/Components/UI/NotificationItem.jsx
> +const NotificationItem = ({ avatar, date, title }) => {
NotificationItem stores only user's info ? or something else ?

2022-10-06 10:26 UTC, Kamchybekk commented on src/Components/UI/Button.jsx
> +const Btn = ({ title, onClick, color }) => {
> 

Fixed it in the feature/Button branch. But in general, there should not have been a button

2022-10-06 10:27 UTC, Kamchybekk commented on src/Components/UI/Button.jsx
> +    <Button onClick={onClick} color={color}>
> 

removed from notification item branch

2022-10-06 10:35 UTC, Kamchybekk commented on src/Components/UI/NotificationItem.jsx
> +      <DateAdded>Sep 15 at 13:23 PM</DateAdded>
Кийин пользовательдин аватары менен ник неймин в будущем башка жерден дагы колдонобузда ошол учун озунчо жазгам

2022-10-06 10:37 UTC, Kamchybekk commented on src/Components/UI/NotificationItem.jsx
> +const NotificationItem = ({ avatar, date, title }) => {
?

2022-10-10 05:53 UTC, songhee24 requested changes

2022-10-10 05:53 UTC, songhee24 commented on src/Components/UI/NotificationItem.jsx
> +const NotificationItem = ({ titleBoard, nameColumn }) => {
<img width="321" alt="Screen Shot 2022-10-10 at 11 53 03" src="https://user-images.githubusercontent.com/44497623/194805417-3fa4a4ee-ce33-4bca-9af8-3465695b9f09.png">
THATS ALSO PROPS IN NOTIFICATION ITEM

2022-10-10 08:22 UTC, merged