Feature/button
peaksoft-school/js6-task-tracker pull request #2
Opened 2022-10-06 04:57 UTC by Kamchybekk

2022-10-06 06:35 UTC, aidanasm requested changes

2022-10-06 06:35 UTC, aidanasm commented on src/App.js
> +      <Btn color="#0079BF" title="Sign up" />
Не нужно давать пропс тайтл пусть берет как чилдрен,
Кнопку переименуйте на Button,
Нет варианта кнопки в сером и в красном цвете, 
Кнопка не берет fullwidth

2022-10-06 06:35 UTC, aidanasm commented on src/Components/UI/UserAvatar.jsx
> +const UserAvatar = () => {
Что делает userAvatar  в бранче баттон

2022-10-06 06:35 UTC, aidanasm commented on src/Components/UI/UserName.jsx
> +  return <StyledUserName>Nazira Nazirova</StyledUserName>;
Тоже самое что и userAvatar

2022-10-06 06:35 UTC, aidanasm commented on src/Components/UI/UserName.jsx
> +  return <StyledUserName>Nazira Nazirova</StyledUserName>;
userName почему статичный?

2022-10-06 06:35 UTC, aidanasm commented on src/Components/UI/UserAvatar.jsx
> +import photoAvatar from "../../assets/images/avatarPhotoo.jpg";
Статичное фото

2022-10-06 12:50 UTC, songhee24 commented
your branch has conflicts also

2022-10-07 06:48 UTC, aidanasm requested changes

2022-10-07 06:48 UTC, aidanasm commented on src/Components/UI/GrayButtons.jsx
> +      <IconButton src={iconButton} /> {children}
будет лучше если будет просто Icon

2022-10-07 06:48 UTC, aidanasm commented on src/Components/UI/Button.jsx
> +      props.hoverColor ? props.hoverColor : "#005688"};
как пропс приходит только hover,  а не hoverColor

2022-10-07 06:48 UTC, aidanasm commented on src/Components/UI/Button.jsx
> +    background-color: ${(props) =>
можете добавить транзишн для плавного hover

2022-10-10 11:51 UTC, merged