Feature/create board
peaksoft-school/js6-task-tracker pull request #40
Opened 2022-10-28 05:10 UTC by parallelnyi

2022-10-31 07:40 UTC, arzybekb requested changes

2022-10-31 07:40 UTC, arzybekb commented on src/Components/CreateBoard.jsx
> +   const [Choose, setChoose] = useState(false)
c маленькой надо и не понятное имя для стейта choose what?
`const [choose, setChoose] = useState(false)` и если стейт Boolean то надо начинать с is

2022-10-31 07:40 UTC, arzybekb commented on src/Components/CreateBoard.jsx
> +                     <div style={{ backgroundImage: `url(${Board1})` }} />
фотографии не кликабельные почему то

2022-10-31 07:40 UTC, arzybekb commented on src/Components/CreateBoard.jsx
> +                     {COLORS.map((color, index) => (
colors тоже не кликабельные почему то

2022-10-31 07:40 UTC, arzybekb commented on src/Components/CreateBoard.jsx
> +
Не по дизайну сделано [
![image](https://user-images.githubusercontent.com/82923090/198955393-342a4fdd-77ae-46db-b3fa-13f233f07071.png)
](url) вот дизайн

2022-11-04 07:20 UTC, songhee24 requested changes

2022-11-04 07:20 UTC, songhee24 commented on src/Components/CreateBoard.jsx
> +
<img width="888" alt="Screen Shot 2022-11-04 at 13 13 58" src="https://user-images.githubusercontent.com/44497623/199915019-7caaf449-372c-415f-bd98-482df670c7b4.png">
может когда я что то выбрал тоже всегда галочку выборки поставить

2022-11-04 07:20 UTC, songhee24 commented on src/Components/CreateBoard.jsx
> +
как при выборке цвета

2022-11-04 07:20 UTC, songhee24 commented on src/Components/CreateBoard.jsx
> +function CreateBoard() {
а еще совсем не вижу поднятия состояние когда выбрал все значения и нажал создать

2022-11-21 08:14 UTC, merged