Feature/navigation
peaksoft-school/js6-task-tracker pull request #43
Opened 2022-11-01 08:25 UTC by Kamchybekk

2022-11-02 08:28 UTC, arzybekb requested changes

2022-11-02 08:28 UTC, arzybekb commented on src/Components/Authorizaiton/Validation.jsx
> +         message: "Бир ар кыйыныраак пароль тап акя",
https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fi.etsystatic.com%2F14449774%2Fr%2Fil%2Fa6c125%2F1838194802%2Fil_fullxfull.1838194802_9b9o.jpg&f=1&nofb=1&ipt=f96238495194fa4c4f3f3029dfaf3057a61f38b9bc8cdc9ad9ed5a6781e9d209&ipo=images

2022-11-02 08:28 UTC, arzybekb commented on src/utilits/helpers/General.js
> +export const LocalStorage = {
src/utils/helpers/localStorageHelpers.js

2022-11-02 08:28 UTC, arzybekb commented on src/api/auth.js
> +export const axiosInstance = axios.create({
axiosInstance мындай болбойт сразу айтып коёюн

2022-11-02 08:28 UTC, arzybekb commented on src/store/AuthSlice.jsx
> +export const login = createAsyncThunk(
tuura emes account bolso belyi ekran bolup kalyp atat

2022-11-02 08:28 UTC, arzybekb commented on src/api/auth.js
> +   baseURL: "http://18.192.179.151",
url алмаштыргыла мен жаны swagger жоноттум

2022-11-02 08:43 UTC, Kamchybekk commented on src/utilits/helpers/General.js
> +export const LocalStorage = {
fixed

2022-11-02 08:43 UTC, Kamchybekk commented on src/api/auth.js
> +export const axiosInstance = axios.create({
Түшүнбөй калдым кандай кылып оңдойун

2022-11-02 09:53 UTC, Kamchybekk commented on src/api/auth.js
> +   baseURL: "http://18.192.179.151",
fixed

2022-11-03 06:02 UTC, Kamchybekk commented on src/api/auth.js
> +   baseURL: "http://18.192.179.151",
fixed

2022-11-03 06:02 UTC, Kamchybekk commented on src/store/AuthSlice.jsx
> +export const login = createAsyncThunk(
fixed

2022-11-05 12:35 UTC, merged