table ui-component is done
peaksoft-school/js6-task-tracker pull request #7
Opened 2022-10-07 06:34 UTC by parallelnyi

2022-10-07 07:46 UTC, aidanasm requested changes

2022-10-07 07:46 UTC, aidanasm commented on src/Components/UI/Table.jsx
> +   const columns = [
это не должно быть статичным

2022-10-07 07:46 UTC, aidanasm commented on src/Components/UI/data.js
> +export const tableData = [
это зачем

2022-10-07 07:46 UTC, aidanasm commented on src/Components/UI/Table.jsx
> +                  {columns.map((head) => (
таблица не имеет стилей как на фигме

2022-10-13 06:52 UTC, closed without merging

2022-10-13 06:52 UTC, parallelnyi commented
fdsa